* Архитектура игры
** Сущности
*** Мир
   Состояние всей игры -- сохраняемое и загружаемое.
   + Генератор глобальных идентификаторов
      Идентификатор (для простоты какое-то число) уникальный во всём мире.
      Зная его, можно найти "настоящий" объект.
   + Глобальная карта мира
     Соответствие глобальных идентификаторов координатам.
     Не всем глобальным идентификаторам соответствуют координаты в мире.
   + Карта объектов
     Соответствие глобальных идентификаторов объектам.
     Каждому объекту соответствует уникальный глобальный идентификатор, а также
     некая внешняя информация.
*** Внешняя информация об объекте
   То, к чему нет доступа у самого объекта.
   + Генератор локальных идентификаторов
     Объекты не знают настоящих глобальных идентификаторов.
     У всех других объектов, с которыми взаимодействует текущий, есть локальный
     идентификатор.
     У объекта нет доступа к генератору; он используется снаружи чтобы
     присваивать идентификаторы.
   + Соответствие идентификаторов
     Соответствие локальных идентификаторов глобальным.
     Каждому другому объекту, который известен текущему, соответствует какой-то
     его настоящий глобальный и локальный идентификаторы. Соответствие
     используется для преобразования в обе стороны.
   + Искуственный интеллект (плохое название)
     Может быть в двух вариациях:
     + Не имеет сохраняемого состояния но имеет (возможно как-то ограниченный)
       доступ к внешнему миру. Предполагается что это управление от игрока.
     + Обязан поддерживать своё полное сохранение, не имеет доступа ко внешнему
       миру кроме генератора случайных чисел -- собственно "искуственный
       интеллект".
*** Управление от игрока
   (не продумывалось)
*** Искуственный интеллект
   Сохраняемый/загружаемый объект. Поддерживает две функции:
   + Воспринять: принимает субъективный мир, управляемый объект, старое своё
     состояние и произошедшее событие. Возвращает новое своё состояние.
   + Действовать: принимает текущее состояние своего хода и своё
     состояние. Возвращает действие.
   Обе функции имеют доступ к генератору случайных чисел.
*** Субъективный мир
   Отражение реального мира, своё у каждого объекта -- то, каким мир виден с его
   стороны. Не сохраняется, его возможно получить из текущего состояния мира.
   + Локальная карта.
     Соответствие локальных идентификаторов координатам.
     Так же как и с глобальной -- не всем идентификаторам соответствуют
     координаты в мире.
   + Моя позиция.
*** Объект
   Состоит из имени, внешнего вида и списка атрибутов. Внешний вид это (ещё не
   продумано, пока случайное число). Атрибуты:
   + Существо
     Стандартный набор параметров для существа в мире -- HP, инвентарь, что в
     руках и прочее.
     Если нет этого атрибута, объекту невозможно причинить вред (в классическом
     смысле), у него нет чувств (не получает событий о мире).
   + Оружие
     Наносимый урон. Если есть атрибут оружия, объект можно держать в руке.
   + Возможно использовать
     Если есть атрибут, можно "взаимодействовать" с предметом. Его интеллект
     получит сообщение о взаимодействии и может выполнить действия.
   + ...
*** Заявка на действие
   Действие, возможное в данной системе правил. Одна из штук которые надо менять
   когда мы хотим сделать другую систему правил. Примеры:
   + Передвинуться на X
   + Ударить Y
   + ...
   Действия заявляются искуственным интеллектом. Всё происходит в локальных
   координатах и с локальными идентификаторами.
*** Результат действия
   То, что реально произошло в мире в результате действия. В глобальных
   идентификаторах и координатах.
*** Событие
   То, что произошло в мире, глазами объекта. Примеры:
   + Y получил Z урона
   + X перешёл на клетку M.
   + ...
   События тоже только локальные.
*** Состояние хода
    Зависит от конкретной системы правил. Например инициатива и какие фазы хода
    потрачены (Move и Standard для D&D, скажем). Обновляется после выполнения
    заявки на действие.
** Ход игры
*** Общее описание
   + Загружается мир, включая состояния искуственных интеллектов. Генерируются
     субъективные миры для всех объектов у которых есть чувства.
   + Смотря от системы правил решается порядок хода.
   + В порядке хода:
     + От искуственного интеллекта объекта получается текущая заявка на
       действие.
     + Действие осуществляется, возможно с провалом, не так хорошо как хотелось
       и.т.д. Генерируется результат действия, обновляется мир и затронутые
       объекты. Для объекта обновляется его состояние хода.
     + Для каждого объекта с чувствами результат действия преобразуется в
       событие, если он мог его наблюдать. Событие отдаётся искуственным
       интеллектам, они обновляют себя. В том числе событие отдаётся тому кто
       заявил действие.
*** Пример действия
    + Объект-существо A (глобальный номер 14) заявляет что хочет создать
      файрбол, летящий по направлению такому-то (на самом деле в существо B,
      глобальный номер 88).
    + Действие осуществляется, на карте появляется новый объект, с чувством
      осязания, с искуственным интеллектом который всё время двигает объект
      вперёд и взрывается когда чувствует касание впереди себя. Глобальный
      номер 42. Действие заняло весь ход, состояние хода у A обновляется.
    + Новый объект видят A, у него новый локальный номер 7, и B, с новым
      локальным номером 8. Он появляется у них на локальных картах.
    + Ходит файрбол. Его интеллект даёт заявку на движение вперёд. Заявка
      выполняется, все получают события о передвижении. Ход файрбола
      продолжается. Его интеллект получает кроме события о перемещении себя
      событие касания с B. Таким образом он начинает видеть B, с новым локальным
      номером 1. B появляется на локальной карте файрбола.
    + Интеллект файрбола решает взорваться, поскольку видит кого-то. Заявка
      исполняется, файрбол взрывается. B получает урон. Все получают событие
      исчезновения файрбола, он исчезает у них с локальных карт. После получения
      всеми события файрбол удаляется из мира, из соответствий A и B
      (соответственно номера 7 и 8 у них освобождаются). Также B получает
      событие о получении 42 урона.
